// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_Stephany_2018_0654.DAL;

namespace P2_AP1_Stephany_2018_0654.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211110020556_CambiosOnCreating")]
    partial class CambiosOnCreating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_Stephany_2018_0654.Entidades.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionProyecto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyecto");
                });

            modelBuilder.Entity("P2_AP1_Stephany_2018_0654.Entidades.ProyectoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("TareasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("ProyectoDetalle");
                });

            modelBuilder.Entity("P2_AP1_Stephany_2018_0654.Entidades.Tareas", b =>
                {
                    b.Property<int>("TareasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<int>("TiempoTarea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TareasId");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            TareasId = 1,
                            FechaIngreso = new DateTime(2021, 11, 10, 22, 5, 55, 733, DateTimeKind.Local).AddTicks(4846),
                            TiempoTarea = 0,
                            TipoTarea = "Analisis"
                        },
                        new
                        {
                            TareasId = 2,
                            FechaIngreso = new DateTime(2021, 11, 10, 22, 5, 55, 733, DateTimeKind.Local).AddTicks(5004),
                            TiempoTarea = 0,
                            TipoTarea = "Diseño"
                        },
                        new
                        {
                            TareasId = 3,
                            FechaIngreso = new DateTime(2021, 11, 10, 22, 5, 55, 733, DateTimeKind.Local).AddTicks(5009),
                            TiempoTarea = 0,
                            TipoTarea = "Programacion"
                        },
                        new
                        {
                            TareasId = 4,
                            FechaIngreso = new DateTime(2021, 11, 10, 22, 5, 55, 733, DateTimeKind.Local).AddTicks(5012),
                            TiempoTarea = 0,
                            TipoTarea = "Prueba"
                        });
                });

            modelBuilder.Entity("P2_AP1_Stephany_2018_0654.Entidades.ProyectoDetalle", b =>
                {
                    b.HasOne("P2_AP1_Stephany_2018_0654.Entidades.Proyecto", null)
                        .WithMany("Detalle")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P2_AP1_Stephany_2018_0654.Entidades.Proyecto", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
